openapi: 3.0.3
info:
  title: Sewa Asri
  description: |-
    Sewa Asri adalah aplikasi mobile yang dapat digunakan untuk booking dan mencari villa terdekat dengan praktis.
  termsOfService: http://sewasri.org/terms/
  contact:
    email: asriteam@sewasri.org
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Sewa Asri
  url: http://sewasri.org
servers:
  - url: http://localhost:8080/api/
tags:
  - name: user
    description: Operations about user
paths:
  /villa:
    get:
      tags:
        - villa
      summary: Get All villa
      description: Get All villa
      operationId: Find All villa
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/villaArray'
        '404':
          description: villa not found
    post:
      tags:
        - villa
      summary: create new villa
      description: Add a new villa
      operationId: addvilla
      requestBody:
        description: Create a villa villa in the booking
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/villa'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/villa'
        '405':
          description: Invalid input
      security:
        - villabooking_auth:
            - write:villa's
            - read:villa's
  /villa/:{villaId}:
    put:
      tags:
        - villa
      summary: Update an existing villa
      description: Update an existing villa by Id
      operationId: updatevilla
      requestBody:
        description: Update an existent villa in booking
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/villa'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/villa'
        '400':
          description: Invalid ID supplied
        '404':
          description: villa not found
        '405':
          description: Validation exception
      security:
        - villabooking_auth:
            - write:villas
            - read:villas

  /villa/findByStatus:
    get:
      tags:
        - villa
      summary: Finds villas by status
      description: Multiple status values can be provided with comma separated strings
      operationId: findvillasByStatus
      parameters:
        - name: status
          in: query
          description: Status values that need to be considered for filter
          required: false
          explode: true
          schema:
            type: string
            default: available
            enum:
              - available
              - pending
              - sold
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/villaArray'
        '400':
          description: Invalid status value
      security:
        - villabooking_auth:
            - write:villas
            - read:villas
  /villa/findByTags:
    get:
      tags:
        - villa
      summary: Finds villas by tags
      description: Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
      operationId: findvillasByTags
      parameters:
        - name: status
          in: query
          description: Status values that need to be considered for filter
          required: false
          explode: true
          schema:
            type: string
            default: available
            enum:
              - Termurah
              - Termahal
              - Dua kamar
              - Tiga Kamar
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/villaArray'
        '400':
          description: Invalid tag value
      security:
        - villabooking_auth:
            - write:villas
            - read:villas
  /villa/{villaId}:
    get:
      tags:
        - villa
      summary: Find villa by ID
      description: Returns a single detail villa
      operationId: getvillaById
      parameters:
        - name: villaId
          in: path
          description: ID of villa to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/villa'
        '400':
          description: Invalid ID supplied
        '404':
          description: villa not found
      security:
        - api_key: [ ]
        - villabooking_auth:
            - write:villas
            - read:villas
    delete:
      tags:
        - villa
      summary: Deletes a villa
      description: delete a villa
      operationId: deletevilla
      parameters:
        - name: api_key
          in: header
          description: ''
          required: false
          schema:
            type: string
        - name: villaId
          in: path
          description: villa id to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '400':
          description: Invalid villa value
      security:
        - villabooking_auth:
            - write:villas
            - read:villas
  /villa/{villaId}/uploadImage:
    post:
      tags:
        - villa
      summary: uploads an image
      description: ''
      operationId: uploadFile
      parameters:
        - name: villaId
          in: path
          description: ID of villa to update
          required: true
          schema:
            type: integer
            format: int64
        - name: additionalMetadata
          in: query
          description: Additional Metadata
          required: false
          schema:
            type: string
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      security:
        - villabooking_auth:
            - write:villas
            - read:villas

components:
  schemas:
    Address:
      type: object
      properties:
        street:
          type: string
          example: Jl gunung 123
        city:
          type: string
          example: Bali
        state:
          type: string
          example: Indonesia
        zip:
          type: string
          example: '94301'
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Termurah

    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        username:
          type: string
          example: theUser
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: James
        email:
          type: string
          example: john@email.com
        password:
          type: string
          example: "undefined"
        phone:
          type: string
          example: '12345'
        isAdmin:
          type: boolean
          description: is Admin
          format: int32
          example: false
    Tag:
      type: object
      properties:
        name:
          type: string
        termurah:
          type: string
        termahal:
          type: string
        terdekat:
          type: string
        terjauh :
          type : string
        terpopuler:
          type: string
        dua kamar:
          type : string
        tiga kamar:
          type : string

    villa:
      required:
        - name
        - photoUrls
        - feature satu
        - feature dua
        - pengelola
        - ulasan
        - rating
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        Title villa:
          type: string
          example: Villa Pesona Lestari
        photoUrls:
          type: array
          example: [img1,img2]
        prices:
          type: integer
          example: 7.200.000 #/Malam
        location:
          type: string
          example: Banten
        Description:
          type: string
          example: ini description villa
        feature satu :
          type: array
          example: [2 kamar tidur, 2 kamar mandi]
        status:
          type: string
          description: villa status in the booking
          enum:
            - available
            - pending
            - sold
        pengelola :
          type: string
          example : bapak Udin
        rating :
          type: integer
          example: 4.8
        ulasan :
          type: string
          example : 78 ulasan
        address :
          type: string
          example: alamat lengkap
    villaArray:
        required:
          - name
          - photoUrls
        type: object
        properties:
          VillaId:
            type: integer
            format: int64
            example: [ 10, 20, 30, 40 ]
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
  requestBodies:
    villa:
      description: villa object that needs to be added to the booking
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/villa'
    UserArray:
      description: List of user object
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/User'
  securitySchemes:
    villabooking_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://villabooking3.swagger.io/oauth/authorize
          scopes:
            write:villas: modify villas in your account
            read:villas: read your villas
    api_key:
      type: apiKey
      name: api_key
      in: header