openapi: 3.0.2
info:
  title: "Sewa Asri API"
  description: "Sewa Asri adalah aplikasi mobile yang dapat digunakan untuk booking dan mencari villa terdekat dengan praktis."
  version: "1.0"
  termsOfService: "https://sewasri.org/terms"
  contact:
    name: "Sewa Asri API"
    url: "https://sewasri.org/api/v1"
    email: "some_email@gmail.com"
  license:
    name: "CC Attribution-ShareAlike 4.0 (CC BY-SA 4.0)"
    url: "https://openweathermap.org/price"
paths: {}
servers:
  - url: https://{environment}.sewasri.org:{port}/api/v1/
    description: The production API server
    variables:
      environment:
        enum:
          - 'admin'
          - 'www'
          - 'api'
        default: api
        description: this value is assigned by the service provider, in this example `gigantic-server.com`
      port:
        enum:
          - '8800'
          - '443'
        default: '8800'
